### ISSUE TITLE
ACLsync file permissie is fout

### ISSUE THREAD

**Issue by baszoetekouw** [SURFscz/SRAM-deploy#345]
Als er een update van een acl is:
```
Sep 14 15:44:59 lb-af1 systemd[1]: Starting SRAM HAproxy ACL syncer...
Sep 14 15:44:59 lb-af1 haproxy[56250]: 10.16.0.20:33228 [14/Sep/2022:15:44:59.635] fe_https~ sbs/server-1 0/0/1/8/9 200 867 - - --NI 2/1/0/0/0 0/0 "GET /api/plsc/ip_ranges HTTP/1.1"
Sep 14 15:44:59 lb-af1 python[97498]: Adding acl `8.8.8.9/32`
Sep 14 15:44:59 lb-af1 python[97498]: Traceback (most recent call last):
Sep 14 15:44:59 lb-af1 python[97498]:   File "/opt/aclsync/./plsc/haproxy_aclsync.py", line 108, in <module>
Sep 14 15:44:59 lb-af1 python[97498]:     main()
Sep 14 15:44:59 lb-af1 python[97498]:   File "/opt/aclsync/./plsc/haproxy_aclsync.py", line 102, in main
Sep 14 15:44:59 lb-af1 python[97498]:     with open(haproxy.acl_file(), "w") as acl_file:
Sep 14 15:44:59 lb-af1 python[97498]: PermissionError: [Errno 13] Permission denied: '/etc/haproxy/acl_ldap_sbs.cfg'
Sep 14 15:44:59 lb-af1 systemd[1]: sram_aclsync.service: Main process exited, code=exited, status=1/FAILURE
Sep 14 15:44:59 lb-af1 systemd[1]: sram_aclsync.service: Failed with result 'exit-code'.
Sep 14 15:44:59 lb-af1 systemd[1]: Failed to start SRAM HAproxy ACL syncer.
Sep 14 15:45:03 lb-af1 haproxy[56250]: 46.137.46.242:37943 [14/Sep/2022:15:45:03.333] ldap~ ldap/blue-1 31/8/+38 +0 -- 1/1/1/1/0 0/0
```

want de file permissie is:
```
-rw-rw----  1 root haproxy  296 Sep  8 09:50 acl_ldap_sbs.cfg
```

**Comment by baszoetekouw** [comment]
Fixed in https://github.com/SURFscz/SRAM-deploy/commit/adaa142e03e8b13297991c4d3963c59306dcf893

**Comment by baszoetekouw** [comment]
And confirmed working on test and acc
